### ISSUE TITLE
FluentPdoPaginator error

### ISSUE THREAD

**Issue by xpalko** [Phauthentic/pagination#8]
1/
$countQuery->select('COUNT(*) AS __count__', true); (line 54)

is it important to override select values (2nd parametr true)

2/

@param \Envms\FluentPDO\Queries\Common $repository

bad class in doc

**Comment by burzum** [comment]
I've merged your PR, everything fixed?

**Comment by xpalko** [comment]
Thanks, i will check it soon!

**Comment by burzum** [comment]
@xpalko any other issues? I'm closing this ticket, please re-open or create a new one if you find another issue. Ideas to improve the plugin are welcome as well!
